
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 10 18:49:24 CET 2023
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import SymbolTable.*;

/** CUP v0.10k generated parser.
  * @version Tue Jan 10 18:49:24 CET 2023
  */
public class MPParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\120\000\002\003\006\000\002\002\004\000\002\003" +
    "\006\000\002\003\005\000\002\003\004\000\002\003\003" +
    "\000\002\004\006\000\002\004\006\000\002\004\005\000" +
    "\002\004\005\000\002\004\005\000\002\004\004\000\002" +
    "\024\003\000\002\023\003\000\002\005\004\000\002\005" +
    "\003\000\002\007\006\000\002\007\006\000\002\007\005" +
    "\000\002\021\005\000\002\021\005\000\002\021\004\000" +
    "\002\021\003\000\002\015\003\000\002\015\003\000\002" +
    "\015\003\000\002\015\003\000\002\006\004\000\002\006" +
    "\003\000\002\010\007\000\002\010\007\000\002\010\006" +
    "\000\002\010\005\000\002\010\004\000\002\010\006\000" +
    "\002\010\006\000\002\010\005\000\002\010\005\000\002" +
    "\010\007\000\002\010\007\000\002\010\006\000\002\010" +
    "\006\000\002\010\006\000\002\010\005\000\002\010\004" +
    "\000\002\010\003\000\002\011\005\000\002\011\005\000" +
    "\002\011\003\000\002\012\005\000\002\012\005\000\002" +
    "\012\003\000\002\013\005\000\002\013\005\000\002\013" +
    "\003\000\002\014\003\000\002\014\003\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\014\003\000" +
    "\002\016\005\000\002\016\005\000\002\016\005\000\002" +
    "\016\005\000\002\016\003\000\002\017\005\000\002\017" +
    "\005\000\002\017\005\000\002\017\005\000\002\017\003" +
    "\000\002\020\003\000\002\020\003\000\002\020\005\000" +
    "\002\020\005\000\002\020\004\000\002\022\003\000\002" +
    "\022\003\000\002\022\003\000\002\022\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\165\000\006\003\005\004\006\001\002\000\004\002" +
    "\167\001\002\000\004\002\ufffc\001\002\000\006\003\007" +
    "\015\010\001\002\000\004\002\ufffd\001\002\000\006\003" +
    "\011\016\012\001\002\000\004\002\ufffe\001\002\000\006" +
    "\003\013\017\016\001\002\000\004\002\uffff\001\002\000" +
    "\004\002\001\001\002\000\014\003\030\011\020\013\017" +
    "\017\016\041\027\001\002\000\014\003\ufff5\011\ufff5\013" +
    "\ufff5\017\ufff5\041\ufff5\001\002\000\006\003\153\015\154" +
    "\001\002\000\014\003\144\011\020\013\017\017\016\041" +
    "\121\001\002\000\020\003\uffd4\011\uffd4\012\uffd4\013\uffd4" +
    "\017\uffd4\020\uffd4\041\uffd4\001\002\000\010\036\126\040" +
    "\130\041\127\001\002\000\016\003\124\011\020\013\017" +
    "\017\016\020\116\041\121\001\002\000\016\003\115\011" +
    "\020\013\017\017\016\020\116\041\027\001\002\000\016" +
    "\003\ufff2\011\ufff2\013\ufff2\017\ufff2\020\ufff2\041\ufff2\001" +
    "\002\000\020\003\uffe5\011\uffe5\012\uffe5\013\uffe5\017\uffe5" +
    "\020\uffe5\041\uffe5\001\002\000\012\036\uffeb\037\033\040" +
    "\uffeb\041\uffeb\001\002\000\024\002\ufff6\003\ufff6\011\ufff6" +
    "\012\ufff6\013\ufff6\017\ufff6\020\ufff6\037\031\041\ufff6\001" +
    "\002\000\004\003\032\001\002\000\020\003\uffdc\011\uffdc" +
    "\012\uffdc\013\uffdc\017\uffdc\020\uffdc\041\uffdc\001\002\000" +
    "\020\003\046\015\035\041\044\042\051\043\043\044\042" +
    "\045\040\001\002\000\040\003\uffb9\016\uffb9\021\uffb9\022" +
    "\uffb9\023\uffb9\024\uffb9\025\uffb9\026\uffb9\027\uffb9\030\uffb9" +
    "\031\uffb9\032\uffb9\033\uffb9\034\uffb9\035\uffb9\001\002\000" +
    "\020\003\110\015\035\041\044\042\051\043\043\044\042" +
    "\045\040\001\002\000\034\003\uffcb\016\uffcb\021\uffcb\022" +
    "\uffcb\023\073\025\100\027\077\030\075\031\070\032\071" +
    "\033\074\034\072\035\uffcb\001\002\000\014\003\uffd1\016" +
    "\uffd1\021\065\022\uffd1\035\uffd1\001\002\000\040\003\uffb2" +
    "\016\uffb2\021\uffb2\022\uffb2\023\uffb2\024\uffb2\025\uffb2\026" +
    "\uffb2\027\uffb2\030\uffb2\031\uffb2\032\uffb2\033\uffb2\034\uffb2" +
    "\035\uffb2\001\002\000\010\003\060\022\062\035\061\001" +
    "\002\000\040\003\uffb3\016\uffb3\021\uffb3\022\uffb3\023\uffb3" +
    "\024\uffb3\025\uffb3\026\uffb3\027\uffb3\030\uffb3\031\uffb3\032" +
    "\uffb3\033\uffb3\034\uffb3\035\uffb3\001\002\000\040\003\uffb4" +
    "\016\uffb4\021\uffb4\022\uffb4\023\uffb4\024\uffb4\025\uffb4\026" +
    "\uffb4\027\uffb4\030\uffb4\031\uffb4\032\uffb4\033\uffb4\034\uffb4" +
    "\035\uffb4\001\002\000\040\003\uffba\016\uffba\021\uffba\022" +
    "\uffba\023\uffba\024\uffba\025\uffba\026\uffba\027\uffba\030\uffba" +
    "\031\uffba\032\uffba\033\uffba\034\uffba\035\uffba\001\002\000" +
    "\040\003\uffc0\016\uffc0\021\uffc0\022\uffc0\023\uffc0\024\052" +
    "\025\uffc0\026\053\027\uffc0\030\uffc0\031\uffc0\032\uffc0\033" +
    "\uffc0\034\uffc0\035\uffc0\001\002\000\020\003\uffdd\011\uffdd" +
    "\012\uffdd\013\uffdd\017\uffdd\020\uffdd\041\uffdd\001\002\000" +
    "\040\003\uffbb\016\uffbb\021\uffbb\022\uffbb\023\uffbb\024\uffbb" +
    "\025\uffbb\026\uffbb\027\uffbb\030\uffbb\031\uffbb\032\uffbb\033" +
    "\uffbb\034\uffbb\035\uffbb\001\002\000\014\003\uffce\016\uffce" +
    "\021\uffce\022\uffce\035\uffce\001\002\000\040\003\uffb5\016" +
    "\uffb5\021\uffb5\022\uffb5\023\uffb5\024\uffb5\025\uffb5\026\uffb5" +
    "\027\uffb5\030\uffb5\031\uffb5\032\uffb5\033\uffb5\034\uffb5\035" +
    "\uffb5\001\002\000\020\003\056\015\035\041\044\042\051" +
    "\043\043\044\042\045\040\001\002\000\020\003\054\015" +
    "\035\041\044\042\051\043\043\044\042\045\040\001\002" +
    "\000\040\003\uffbc\016\uffbc\021\uffbc\022\uffbc\023\uffbc\024" +
    "\uffbc\025\uffbc\026\uffbc\027\uffbc\030\uffbc\031\uffbc\032\uffbc" +
    "\033\uffbc\034\uffbc\035\uffbc\001\002\000\040\003\uffbd\016" +
    "\uffbd\021\uffbd\022\uffbd\023\uffbd\024\uffbd\025\uffbd\026\uffbd" +
    "\027\uffbd\030\uffbd\031\uffbd\032\uffbd\033\uffbd\034\uffbd\035" +
    "\uffbd\001\002\000\040\003\uffbe\016\uffbe\021\uffbe\022\uffbe" +
    "\023\uffbe\024\uffbe\025\uffbe\026\uffbe\027\uffbe\030\uffbe\031" +
    "\uffbe\032\uffbe\033\uffbe\034\uffbe\035\uffbe\001\002\000\040" +
    "\003\uffbf\016\uffbf\021\uffbf\022\uffbf\023\uffbf\024\uffbf\025" +
    "\uffbf\026\uffbf\027\uffbf\030\uffbf\031\uffbf\032\uffbf\033\uffbf" +
    "\034\uffbf\035\uffbf\001\002\000\020\003\uffde\011\uffde\012" +
    "\uffde\013\uffde\017\uffde\020\uffde\041\uffde\001\002\000\020" +
    "\003\uffdf\011\uffdf\012\uffdf\013\uffdf\017\uffdf\020\uffdf\041" +
    "\uffdf\001\002\000\020\003\064\015\035\041\044\042\051" +
    "\043\043\044\042\045\040\001\002\000\014\003\uffd3\016" +
    "\uffd3\021\065\022\uffd3\035\uffd3\001\002\000\012\003\uffd2" +
    "\016\uffd2\022\uffd2\035\uffd2\001\002\000\020\003\066\015" +
    "\035\041\044\042\051\043\043\044\042\045\040\001\002" +
    "\000\014\003\uffcf\016\uffcf\021\uffcf\022\uffcf\035\uffcf\001" +
    "\002\000\014\003\uffd0\016\uffd0\021\uffd0\022\uffd0\035\uffd0" +
    "\001\002\000\020\003\uffc6\015\uffc6\041\uffc6\042\uffc6\043" +
    "\uffc6\044\uffc6\045\uffc6\001\002\000\020\003\uffc5\015\uffc5" +
    "\041\uffc5\042\uffc5\043\uffc5\044\uffc5\045\uffc5\001\002\000" +
    "\020\003\uffc7\015\uffc7\041\uffc7\042\uffc7\043\uffc7\044\uffc7" +
    "\045\uffc7\001\002\000\020\003\106\015\035\041\044\042" +
    "\051\043\043\044\042\045\040\001\002\000\020\003\uffc8" +
    "\015\uffc8\041\uffc8\042\uffc8\043\uffc8\044\uffc8\045\uffc8\001" +
    "\002\000\020\003\uffc9\015\uffc9\041\uffc9\042\uffc9\043\uffc9" +
    "\044\uffc9\045\uffc9\001\002\000\020\003\104\015\035\041" +
    "\044\042\051\043\043\044\042\045\040\001\002\000\020" +
    "\003\uffca\015\uffca\041\uffca\042\uffca\043\uffca\044\uffca\045" +
    "\uffca\001\002\000\020\003\102\015\035\041\044\042\051" +
    "\043\043\044\042\045\040\001\002\000\040\003\uffc2\016" +
    "\uffc2\021\uffc2\022\uffc2\023\uffc2\024\052\025\uffc2\026\053" +
    "\027\uffc2\030\uffc2\031\uffc2\032\uffc2\033\uffc2\034\uffc2\035" +
    "\uffc2\001\002\000\034\003\uffc1\016\uffc1\021\uffc1\022\uffc1" +
    "\023\uffc1\025\uffc1\027\uffc1\030\uffc1\031\uffc1\032\uffc1\033" +
    "\uffc1\034\uffc1\035\uffc1\001\002\000\020\003\uffcd\016\uffcd" +
    "\021\uffcd\022\uffcd\023\073\025\100\035\uffcd\001\002\000" +
    "\014\003\uffcc\016\uffcc\021\uffcc\022\uffcc\035\uffcc\001\002" +
    "\000\040\003\uffc4\016\uffc4\021\uffc4\022\uffc4\023\uffc4\024" +
    "\052\025\uffc4\026\053\027\uffc4\030\uffc4\031\uffc4\032\uffc4" +
    "\033\uffc4\034\uffc4\035\uffc4\001\002\000\034\003\uffc3\016" +
    "\uffc3\021\uffc3\022\uffc3\023\uffc3\025\uffc3\027\uffc3\030\uffc3" +
    "\031\uffc3\032\uffc3\033\uffc3\034\uffc3\035\uffc3\001\002\000" +
    "\010\003\111\016\112\022\062\001\002\000\040\003\uffb6" +
    "\016\uffb6\021\uffb6\022\uffb6\023\uffb6\024\uffb6\025\uffb6\026" +
    "\uffb6\027\uffb6\030\uffb6\031\uffb6\032\uffb6\033\uffb6\034\uffb6" +
    "\035\uffb6\001\002\000\040\003\uffb7\016\uffb7\021\uffb7\022" +
    "\uffb7\023\uffb7\024\uffb7\025\uffb7\026\uffb7\027\uffb7\030\uffb7" +
    "\031\uffb7\032\uffb7\033\uffb7\034\uffb7\035\uffb7\001\002\000" +
    "\040\003\uffb8\016\uffb8\021\uffb8\022\uffb8\023\uffb8\024\uffb8" +
    "\025\uffb8\026\uffb8\027\uffb8\030\uffb8\031\uffb8\032\uffb8\033" +
    "\uffb8\034\uffb8\035\uffb8\001\002\000\016\003\122\011\020" +
    "\013\017\017\016\020\116\041\121\001\002\000\016\003" +
    "\ufff3\011\ufff3\013\ufff3\017\ufff3\020\ufff3\041\ufff3\001\002" +
    "\000\024\002\ufff9\003\ufff9\011\ufff9\012\ufff9\013\ufff9\017" +
    "\ufff9\020\ufff9\037\031\041\ufff9\001\002\000\022\002\ufff4" +
    "\003\ufff4\011\ufff4\012\ufff4\013\ufff4\017\ufff4\020\ufff4\041" +
    "\ufff4\001\002\000\022\002\ufff7\003\ufff7\011\ufff7\012\ufff7" +
    "\013\ufff7\017\ufff7\020\ufff7\041\ufff7\001\002\000\020\003" +
    "\uffe6\011\uffe6\012\uffe6\013\uffe6\017\uffe6\020\uffe6\041\uffe6" +
    "\001\002\000\004\037\033\001\002\000\024\002\ufffa\003" +
    "\ufffa\011\ufffa\012\ufffa\013\ufffa\017\ufffa\020\ufffa\037\031" +
    "\041\ufffa\001\002\000\022\002\ufffb\003\ufffb\011\ufffb\012" +
    "\ufffb\013\ufffb\017\ufffb\020\ufffb\041\ufffb\001\002\000\004" +
    "\037\031\001\002\000\022\002\ufff8\003\ufff8\011\ufff8\012" +
    "\ufff8\013\ufff8\017\ufff8\020\ufff8\041\ufff8\001\002\000\006" +
    "\003\142\041\141\001\002\000\014\003\uffec\016\uffec\036" +
    "\uffec\040\uffec\041\uffec\001\002\000\014\003\132\005\136" +
    "\006\135\007\133\010\134\001\002\000\006\003\137\035" +
    "\140\001\002\000\016\003\uffef\011\uffef\013\uffef\017\uffef" +
    "\020\uffef\041\uffef\001\002\000\006\003\uffe8\035\uffe8\001" +
    "\002\000\006\003\uffe7\035\uffe7\001\002\000\006\003\uffe9" +
    "\035\uffe9\001\002\000\006\003\uffea\035\uffea\001\002\000" +
    "\016\003\ufff0\011\ufff0\013\ufff0\017\ufff0\020\ufff0\041\ufff0" +
    "\001\002\000\016\003\ufff1\011\ufff1\013\ufff1\017\ufff1\020" +
    "\ufff1\041\ufff1\001\002\000\014\003\uffee\016\uffee\036\uffee" +
    "\040\uffee\041\uffee\001\002\000\014\003\uffed\016\uffed\036" +
    "\uffed\040\uffed\041\uffed\001\002\000\016\003\145\011\020" +
    "\012\146\013\017\017\016\041\121\001\002\000\022\003" +
    "\uffe0\011\uffe0\012\uffe0\013\uffe0\017\uffe0\020\uffe0\037\031" +
    "\041\uffe0\001\002\000\022\003\uffe1\011\uffe1\012\uffe1\013" +
    "\uffe1\017\uffe1\020\uffe1\037\031\041\uffe1\001\002\000\020" +
    "\003\150\015\035\041\044\042\051\043\043\044\042\045" +
    "\040\001\002\000\010\003\151\022\062\035\152\001\002" +
    "\000\020\003\uffe2\011\uffe2\012\uffe2\013\uffe2\017\uffe2\020" +
    "\uffe2\041\uffe2\001\002\000\020\003\uffe3\011\uffe3\012\uffe3" +
    "\013\uffe3\017\uffe3\020\uffe3\041\uffe3\001\002\000\020\003" +
    "\uffe4\011\uffe4\012\uffe4\013\uffe4\017\uffe4\020\uffe4\041\uffe4" +
    "\001\002\000\020\003\uffd5\011\uffd5\012\uffd5\013\uffd5\017" +
    "\uffd5\020\uffd5\041\uffd5\001\002\000\010\003\156\016\157" +
    "\041\155\001\002\000\012\003\uffeb\016\uffeb\036\uffeb\041" +
    "\uffeb\001\002\000\020\003\uffd6\011\uffd6\012\uffd6\013\uffd6" +
    "\017\uffd6\020\uffd6\041\uffd6\001\002\000\006\003\165\035" +
    "\166\001\002\000\012\003\161\016\162\036\126\041\127" +
    "\001\002\000\020\003\uffd9\011\uffd9\012\uffd9\013\uffd9\017" +
    "\uffd9\020\uffd9\041\uffd9\001\002\000\006\003\163\035\164" +
    "\001\002\000\020\003\uffda\011\uffda\012\uffda\013\uffda\017" +
    "\uffda\020\uffda\041\uffda\001\002\000\020\003\uffdb\011\uffdb" +
    "\012\uffdb\013\uffdb\017\uffdb\020\uffdb\041\uffdb\001\002\000" +
    "\020\003\uffd7\011\uffd7\012\uffd7\013\uffd7\017\uffd7\020\uffd7" +
    "\041\uffd7\001\002\000\020\003\uffd8\011\uffd8\012\uffd8\013" +
    "\uffd8\017\uffd8\020\uffd8\041\uffd8\001\002\000\004\002\000" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\165\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\004\013\024\014\001" +
    "\001\000\002\001\001\000\002\001\001\000\020\004\020" +
    "\005\023\006\022\007\024\010\025\021\021\024\014\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\004\020" +
    "\006\142\010\025\024\014\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\004\020\010\117\023\124\024\014" +
    "\001\001\000\020\004\020\006\112\007\113\010\025\021" +
    "\021\023\116\024\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\011\040\012\036\013\047" +
    "\016\035\017\044\020\046\022\033\001\001\000\002\001" +
    "\001\000\020\011\106\012\036\013\047\016\035\017\044" +
    "\020\046\022\033\001\001\000\004\014\075\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\020\056\022\033\001\001\000" +
    "\006\020\054\022\033\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\012\062\013\047\016\035" +
    "\017\044\020\046\022\033\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\013\066\016\035\017\044\020\046" +
    "\022\033\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\017\104\020\046\022\033\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\016\102\017\044\020\046\022\033" +
    "\001\001\000\002\001\001\000\010\017\100\020\046\022" +
    "\033\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\004\020\010\117\023\122\024" +
    "\014\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\015\130\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\004\020\010\117\024" +
    "\014\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\011\146\012\036\013\047\016\035\017\044\020\046\022" +
    "\033\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\021" +
    "\157\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    symbolTable= new SymbolTable();

    }



        static private FileReader file;
        static private MPLexer scanner;
        static private MPParser parser;

        public static int errNo = 0;
        public static int warnNo = 0;
        public static int nestLevel= 0;
        public static SymbolTable symbolTable;

       public static void main( String[] args )
       {
          try
          {
               file = new FileReader( args[0] );
               scanner = new MPLexer( file );
               parser = new MPParser( scanner );
               parser.parse();
               checkWarnings();
               if ( parser.errNo == 0 && parser.warnNo == 0 )
                   System.out.println( "Analiza zavrsena. U kodu nema gresaka." );
               else
                  System.out.println( "Analiza zavrsena. Broj gresaka: " + parser.errNo
                     + " Broj upozorenja: " + parser.warnNo );
          }
          catch( Exception e )
          {
               System.out.println(e);
          }



       }

        public int getLine(){
            return scanner.getLine();
        }

       private static void checkWarnings(){
          SymbolNode current = symbolTable.getVariables();
          while ( current != null ){
            Variable var = ( Variable ) current;
            if ( var.last_def == -1 && var.last_use == -1 ){
                System.out.println( "Upozorenje: Promenljiva " + var.name +
                    " je deklarisana, ali se nigde ne koristi." );
                warnNo++;
            }else if ( var.last_def > var.last_use ){
                System.out.println( "Upozorenje: Vrednost dodeljena promeljivoj " +
                    var.name + " u liniji " + var.last_def + " se nigde ne koristi." );
                warnNo++;
            }
            current = current.next;
         }
       }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // Const ::= REALCONST 
            {
              Constant RESULT = null;
		int rleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Double r = (Double)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                  RESULT = new Constant( parser.symbolTable.getType( "real" ), r );
                  System.out.println("Redukcija po smeni 43.");
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Const*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // Const ::= BOOLCONST 
            {
              Constant RESULT = null;
		int bleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Boolean b = (Boolean)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                 RESULT = new Constant( parser.symbolTable.getType( "bool" ), b );
                 System.out.println("Redukcija po smeni 42.");
               
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Const*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // Const ::= CHARCONST 
            {
              Constant RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Character c = (Character)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                 RESULT = new Constant( parser.symbolTable.getType( "char" ), c );
                 System.out.println("Redukcija po smeni 41.");
              
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Const*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // Const ::= INTCONST 
            {
              Constant RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                 RESULT = new Constant( parser.symbolTable.getType( "int" ), c );
                 System.out.println("Redukcija po smeni 40.");
              
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Const*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // Factor ::= LP error 
            {
              Type RESULT = null;
		
              System.out.println("Greska u liniji " + parser.getLine() + ": " + 
              	"Nekorektan izraz.");
              parser.errNo++;
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Factor*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // Factor ::= LP Expression error 
            {
              Type RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Type i = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                System.out.println( "Greska u liniji " + parser.getLine() + ": " + 
              	    "Nedostaje ')'.");
                parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Factor*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // Factor ::= LP Expression RP 
            {
              Type RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Type i = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                RESULT = i;
                System.out.println("Redukcija po smeni 39.");
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Factor*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // Factor ::= Const 
            {
              Type RESULT = null;
		int kleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Constant k = (Constant)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                RESULT= k.type;
                System.out.println("Redukcija po smeni 38.");
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Factor*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // Factor ::= ID 
            {
              Type RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
              Variable var = parser.symbolTable.getVar( ime, parser.nestLevel, false );
		      if ( var == null ){
		      	System.out.println( "Greska u liniji " + parser.getLine() + 
		      		": promenljiva " + ime + " nije deklarisana.");
		      	RESULT = parser.symbolTable.getType( "unknown" );
		      	parser.errNo++;
		      }else {
		      	RESULT = var.type;
		      	if ( var.last_def == -1 ){
		      		System.out.println( "Greska u liniji " + parser.getLine() + 
		      			": promenljiva " + ime + " nije inicijalizovana.");
		      		parser.errNo++;
		      	}
		        var.last_use = parser.getLine();
		        System.out.println("Redukcija po smeni 37.");
		      }
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Factor*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // Term ::= Factor 
            {
              Type RESULT = null;
		int fleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type f = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                RESULT=f;
                System.out.println("Redukcija po smeni 36.");
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // Term ::= Term DIV error 
            {
              Type RESULT = null;
		int rleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                       "Operacija: / nije korektno upotrebljena nedostaje drugi operand." );
                RESULT= parser.symbolTable.getType("unknown");
                parser.errNo++; 
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // Term ::= Term DIV Factor 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
           	  if( i1.tkind == Type.UNKNOWN || i2.tkind== Type.UNKNOWN){
                        System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                            "Operator + se ne moze primeniti na uknown tipu ");
                        RESULT= parser.symbolTable.getType("unknown");
                        parser.errNo++;
                }else{
                    if ( i1.tkind == Type.BOOL || i2.tkind == Type.BOOL ){
                        System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Operator + se ne moze primeniti nad operandima tipa " + 
                        i1.name + " i " + i2.name );
                        RESULT= parser.symbolTable.getType("unknown");
                        parser.errNo++;
                    }

                    RESULT = i1.tkind > i2.tkind ?  i1 : i2;
                    System.out.println("Redukcija po smeni 35.");
                }
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // Term ::= Term MUL error 
            {
              Type RESULT = null;
		int rleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Operacija: * nije korektno upotrebljena nad drugim parametrom' " );
                RESULT= parser.symbolTable.getType("unknown");
                parser.errNo++; 
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // Term ::= Term MUL Factor 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
           	    if( i1.tkind == Type.UNKNOWN || i2.tkind== Type.UNKNOWN){
                        System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                            "Operator * se ne moze primeniti na uknown tipu ");
                        RESULT= parser.symbolTable.getType("unknown");
                        parser.errNo++;
                }else{
                    if ( i1.tkind == Type.BOOL || i2.tkind == Type.BOOL ){
                        System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Operator + se ne moze primeniti nad operandima tipa " + 
                        i1.name + " i " + i2.name );
                        RESULT= parser.symbolTable.getType("unknown");
                        parser.errNo++;
                    }

                    RESULT = i1.tkind > i2.tkind ?  i1 : i2;
                    System.out.println("Redukcija po smeni 34.");
                }
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // ArExpression ::= Term 
            {
              Type RESULT = null;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                    RESULT=t.type;
                    System.out.println("Redukcija po smeni 33.");
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*ArExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // ArExpression ::= ArExpression MIN error 
            {
              Type RESULT = null;
		int rleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                            "Operacija: - nije korektno upotrebljena fali drugi operand' " );
                    RESULT= parser.symbolTable.getType("unknown");
                    parser.errNo++; 
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*ArExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // ArExpression ::= ArExpression MIN Term 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                    if( i1.tkind == Type.UNKNOWN || i2.tkind== Type.UNKNOWN){
                           System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                                "Operator - se ne moze primeniti na uknown tipu ");
                            RESULT= parser.symbolTable.getType("unknown");
                            parser.errNo++;
                    }else{
                        if ( i1.tkind == Type.BOOL || i2.tkind == Type.BOOL ){
                            System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                            "Operator - se ne moze primeniti nad operandima tipa " + 
                            i1.name + " i " + i2.name );
                            RESULT= parser.symbolTable.getType("unknown");
                            parser.errNo++;
                        }

                        RESULT = i1.tkind > i2.tkind ?  i1 : i2;
                        System.out.println("Redukcija po smeni 32.");
                    }
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*ArExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // ArExpression ::= ArExpression PLUS error 
            {
              Type RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                            "Operacija: + nije korektno upotrebljena fali drugi operand' " );
                    RESULT= parser.symbolTable.getType("unknown");
                    parser.errNo++; 
                 
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*ArExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // ArExpression ::= ArExpression PLUS Term 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                    if( i1.tkind == Type.UNKNOWN || i2.tkind== Type.UNKNOWN){
                           System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                                "Operator + se ne moze primeniti na uknown tipu ");
                            RESULT= parser.symbolTable.getType("unknown");
                            parser.errNo++;
                    }else{
                        if ( i1.tkind == Type.BOOL || i2.tkind == Type.BOOL ){
                            System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                            "Operator + se ne moze primeniti nad operandima tipa " + 
                            i1.name + " i " + i2.name );
                            RESULT= parser.symbolTable.getType("unknown");
                            parser.errNo++;
                        }

                        RESULT = i1.tkind > i2.tkind ? i1 : i2;
                        System.out.println("Redukcija po smeni 31.");
                    }
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*ArExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // RelOp ::= GREATE 
            {
              Object RESULT = null;
		
                System.out.println("Redukcija po smeni 30.");
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // RelOp ::= GREAT 
            {
              Object RESULT = null;
		
                System.out.println("Redukcija po smeni 29.");
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // RelOp ::= NEQ 
            {
              Object RESULT = null;
		
                System.out.println("Redukcija po smeni 28.");
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // RelOp ::= EQ 
            {
              Object RESULT = null;
		
                System.out.println("Redukcija po smeni 27.");
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // RelOp ::= LESSE 
            {
              Object RESULT = null;
		
                System.out.println("Redukcija po smeni 26.");
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // RelOp ::= LESS 
            {
              Object RESULT = null;
		
                System.out.println("Redukcija po smeni 25.");
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // RelExpression ::= ArExpression 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                        RESULT = i1;
                        System.out.println("Redukcija po smeni 24.");
                    
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // RelExpression ::= ArExpression RelOp error 
            {
              Type RESULT = null;
		int roleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int roright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object ro = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                        System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                                "Relaciona operacija nije korektno upotrebljena fali expression' " );
                        RESULT= parser.symbolTable.getType("unknown");
                        parser.errNo++; 
                    
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // RelExpression ::= ArExpression RelOp ArExpression 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                        if(i1.tkind == Type.UNKNOWN ||  
                                 i2.tkind == Type.UNKNOWN){
                            System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                                "Primenjen relacioni operator nad operandima koji unknown ");
                            RESULT= parser.symbolTable.getType("unknown");
                            parser.errNo++;  
                        }else{
                            if(i1.tkind == Type.BOOL ||  
                                 i2.tkind == Type.BOOL){
                                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                                    "Primenjen relacioni operator nad operandima koji su bool ");
                                RESULT= parser.symbolTable.getType("unknown");
                                parser.errNo++;  
                            }else{
                                RESULT = parser.symbolTable.getType("bool");
                                System.out.println("Redukcija po smeni 23.");
                            }
                        }
                    
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // AndExpression ::= RelExpression 
            {
              Type RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                        RESULT = i.type;
                        System.out.println("Redukcija po smeni 22.");
                    
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*AndExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // AndExpression ::= AndExpression AND error 
            {
              Type RESULT = null;
		
                        System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                                "Nedostaje vrednost za '&&' " );
                        RESULT= parser.symbolTable.getType("unknown");        
                        parser.errNo++; 
                    
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*AndExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // AndExpression ::= AndExpression AND RelExpression 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                        if(i1.tkind != Type.BOOL || i2.tkind != Type.BOOL ){
                            System.out.println("Greska u liniji "+ parser.getLine()+": "+
                                "Primenjen logiÄ?ki operator nad operandima koji nisu bool");
                            RESULT= parser.symbolTable.getType("unknown");        
                            parser.errNo++;
                        }else{
                            RESULT = parser.symbolTable.getType("bool");
                            System.out.println("Redukcija po smeni 21.");
                        }
                        
                    
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*AndExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Expression ::= AndExpression 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                    RESULT = i1.type;
                    System.out.println("Redukcija po smeni 20.");
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Expression ::= Expression OR error 
            {
              Type RESULT = null;
		
                   System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje vrednost za uporedjivanje " );
                    parser.errNo++; 
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Expression ::= Expression OR AndExpression 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                    if(i1.tkind != Type.BOOL || i2.tkind != Type.BOOL ){
                        System.out.println("Greska u liniji "+ parser.getLine()+": "+
                            "Primenjen logiÄ?ki operator nad operandima koji nisu bool");
                        RESULT= parser.symbolTable.getType("unknown");        
                        parser.errNo++;
                    }else{
                        RESULT = parser.symbolTable.getType("bool");
                        System.out.println("Redukcija po smeni 19.");
                    }
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Statement ::= Block 
            {
              Object RESULT = null;
		
                System.out.println("Redukcija po smeni 18.");
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Statement ::= READ error 
            {
              Object RESULT = null;
		int rleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Funkcija: read nije lepo deklarisana " );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Statement ::= READ LP error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nekorektno koriscenje read funkcije : ' namelist ) '" );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Statement ::= READ LP RP error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje promenjiva unutar read" );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Statement ::= READ LP RP DOTCOMMA 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje promenjiva unutar read" );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Statement ::= READ LP NameList error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje ')' nakon izraza " );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Statement ::= READ LP NameList RP error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje ';' nakon izraza " );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Statement ::= READ LP NameList RP DOTCOMMA 
            {
              Object RESULT = null;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		

                 for ( int i=0; i<niz.size(); i++ ){
					String ime = (String) niz.get(i);
                    Variable var = parser.symbolTable.getVar( ime, parser.nestLevel, false );
                    if ( var == null ){
                        System.out.println( "Greska u liniji " + parser.getLine() + 
                            ": promenljiva " + ime + " nije deklarisana.");
                        parser.errNo++;
                    }
                    else{
                        var.last_def = parser.getLine();
                        System.out.println("Redukcija po smeni 17.");
                    }
				 }
                    
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Statement ::= error ASSIGN error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje = za ");
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Statement ::= ID ASSIGN error 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje deklaracija : "+ id );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Statement ::= ID ASSIGN Expression error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje ';' nakon izraza " );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Statement ::= ID ASSIGN Expression DOTCOMMA 
            {
              Object RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Type e = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                    Variable var = parser.symbolTable.getVar( ime, parser.nestLevel, false );
                    if ( var == null ){
                        System.out.println( "Greska u liniji " + parser.getLine() + 
                            ": promenljiva " + ime + " nije deklarisana.");
                        parser.errNo++;
                    }else{
                         if(e.tkind == Type.UNKNOWN){
                            System.out.println( "Greska u liniji " + parser.getLine() + 
                                ": Ne moze se proslediti ne validan expression.");
                            parser.errNo++;
                        }else{
                            
                            if(( e.tkind == Type.BOOL && var.type.tkind != Type.BOOL ) ||
                                    ( e.tkind != Type.BOOL && var.type.tkind == Type.BOOL )
                                ){
                                System.out.println( "Greska u liniji " + parser.getLine() + 
                                ": Neslaganje tipa u naredbi dodele." );
                                parser.errNo++;  
                            }else{
                                if(var.type.conversionDif(e) < 0){
                                    System.out.println( "Greska u liniji " + parser.getLine() + 
                                    ": Ne moze proslediti visi tipa nizem tipu." );
                                    parser.errNo++; 
                                }else{
                                    var.last_def = parser.getLine();
                                    System.out.println("Redukcija po smeni 16.");
                                }
                            }
                        }

                    }
                                    
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Statement ::= REPEAT error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje stetmentList za petlju" );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Statement ::= REPEAT StatementList error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje 'until' za petlju" );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Statement ::= REPEAT StatementList UNTIL error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje  'Expression' u petlji" );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Statement ::= REPEAT StatementList UNTIL Expression error 
            {
              Object RESULT = null;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje ';' nakon izraza " );
                    parser.errNo++;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Statement ::= REPEAT StatementList UNTIL Expression DOTCOMMA 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Type e = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                        if(e.tkind != Type.BOOL){
                            System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                                "Expression izraz u repeat/until mora biti tipa bool ! " );
                            parser.errNo++;
                        }else{
                            System.out.println("Redukcija po smeni 15.");
                        }
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // StatementList ::= Statement 
            {
              Object RESULT = null;
		
                    System.out.println("Redukcija po smeni 14.");
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*StatementList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // StatementList ::= StatementList Statement 
            {
              Object RESULT = null;
		
                    System.out.println("Redukcija po smeni 13.");
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*StatementList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Tip ::= BOOL 
            {
              Type RESULT = null;
		
             RESULT = parser.symbolTable.getType( "bool" );
             System.out.println("Redukcija po smeni 12.");
          
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Tip*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Tip ::= REAL 
            {
              Type RESULT = null;
		
             RESULT = parser.symbolTable.getType( "real" );
             System.out.println("Redukcija po smeni 11.");
          
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Tip*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Tip ::= CHAR 
            {
              Type RESULT = null;
		
             RESULT = parser.symbolTable.getType( "char" );
             System.out.println("Redukcija po smeni 10.");
          
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Tip*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Tip ::= INT 
            {
              Type RESULT = null;
		
             RESULT = parser.symbolTable.getType( "int" );
             System.out.println("Redukcija po smeni 9.");
        
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Tip*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // NameList ::= ID 
            {
              ArrayList RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                    RESULT = new ArrayList();
                    RESULT.add( ime );
                    System.out.println("Redukcija po smeni 8.");
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NameList ::= NameList ID 
            {
              ArrayList RESULT = null;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje simbol ',' " );
                    parser.errNo++;
                    RESULT = niz;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // NameList ::= NameList COMMA error 
            {
              ArrayList RESULT = null;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		
                    System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                        "Nedostaje simbol ',' " );
                    parser.errNo++;
                    RESULT = niz;
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // NameList ::= NameList COMMA ID 
            {
              ArrayList RESULT = null;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                    RESULT = niz;
			 	    RESULT.add( ime );
			 	    System.out.println("Redukcija po smeni 7.");
                
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // VarDecl ::= NameList DOUBLEDOT error 
            {
              Object RESULT = null;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		
					Type t = parser.symbolTable.getType( "unknown" );
					for ( int i=0; i<niz.size(); i++ )
					{
					   String ime = (String) niz.get(i);
					   
					   if ( ! parser.symbolTable.addVar( ime, t, parser.nestLevel ) )
					   {
					   	 System.out.println( "Greska u liniji " + parser.getLine() + ": " + 
                   			"Promenljiva " + ime + " je vec deklarisana." );
            		     parser.errNo++;
					   }
					}
                   System.out.println( "Greska u liniji " + parser.getLine() + ": " + 
                   		"Nekorektno ime tipa." );
            		parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*VarDecl*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // VarDecl ::= NameList DOUBLEDOT Tip error 
            {
              Object RESULT = null;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		

                  // provera za ponovno deklarisanje
                for ( int i=0; i<niz.size(); i++ )
					{
					   String ime = (String) niz.get(i);
					   
					   if ( ! parser.symbolTable.addVar( ime, t, parser.nestLevel ) )
					   {
					   	 System.out.println( "Greska u liniji " + parser.getLine() + ": " + 
                   			"Promenljiva " + ime + " je vec deklarisana." );
            		     parser.errNo++;
					   }
					}
                System.out.println("Greska u liniji " + parser.getLine() + ": " + "Nedostaje ';'.");
                parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*VarDecl*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // VarDecl ::= NameList DOUBLEDOT Tip DOTCOMMA 
            {
              Object RESULT = null;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                boolean flag = true;
                for ( int i=0; i<niz.size(); i++ )
					{
					   String ime = (String) niz.get(i);
					   
					   if ( ! parser.symbolTable.addVar( ime, t,parser.nestLevel ) )
					   {
					   	 System.out.println( "Greska u liniji " + parser.getLine() + ": " + 
                   			"Promenljiva " + ime + " je vec deklarisana." );
            		     parser.errNo++;
            		     flag = false;
            		     break;
					   }
					}
					if(flag){
                        System.out.println("Redukcija po smeni 6.");
                    }
            
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*VarDecl*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // VarList ::= VarDecl 
            {
              Object RESULT = null;
		
            System.out.println("Redukcija po smeni 5.");
         
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*VarList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // VarList ::= VarList VarDecl 
            {
              Object RESULT = null;
		
             System.out.println("Redukcija po smeni 4.");
          
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*VarList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // RVZ ::= RV 
            {
              Object RESULT = null;
		
            parser.nestLevel--;
            System.out.println("Redukcija po smeni 3.");
        
              CUP$MPParser$result = new java_cup.runtime.Symbol(17/*RVZ*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // LVZ ::= LV 
            {
              Object RESULT = null;
		
            parser.nestLevel++;
            System.out.println("Redukcija po smeni 2.");
        
              CUP$MPParser$result = new java_cup.runtime.Symbol(18/*LVZ*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Block ::= LVZ error 
            {
              Object RESULT = null;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                "Nedostaje stetments.");
                parser.errNo++;            
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Block ::= LVZ VarList RVZ 
            {
              Object RESULT = null;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                "Nedostaje stetments.");
                parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Block ::= LVZ StatementList RVZ 
            {
              Object RESULT = null;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
                "Nedostaje deklaracije promenjivih.");
                parser.errNo++;  
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Block ::= LVZ VarList error 
            {
              Object RESULT = null;
		
                 System.out.println("Greska u liniji " + parser.getLine() + ": " +
                    "Nedostaje statment-i." );
                parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Block ::= LVZ VarList StatementList error 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " +
                    "Nedostaje '}'." );
                parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Block ::= LVZ VarList StatementList RVZ 
            {
              Object RESULT = null;
		
            System.out.println("Redukcija po smeni 1.");
         
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Program ::= error 
            {
              Object RESULT = null;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
            		"Nedostaje kljucna rec 'main' na pocetku.");
            	parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Program ::= MAIN error 
            {
              Object RESULT = null;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
            		"Nedostaje '('.");
            	parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Program ::= MAIN LP error 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                System.out.println("Greska u liniji " + parser.getLine() + ": " + 
            		"Nedostaje ')'.");
            	parser.errNo++;
            
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= MAIN LP RP error 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
                System.out.println( "Nedostaje 'Block'" );
                parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= MAIN LP RP Block 
            {
              Object RESULT = null;
		
            System.out.println("Redukcija po smeni 0.");
         
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

