
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 10 18:49:24 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 4;
  public static final int LESSE = 22;
  public static final int GREAT = 23;
  public static final int REPEAT = 7;
  public static final int INT = 3;
  public static final int DOTCOMMA = 27;
  public static final int LESS = 21;
  public static final int WRITE = 10;
  public static final int LV = 13;
  public static final int AND = 15;
  public static final int RV = 14;
  public static final int INTCONST = 32;
  public static final int LP = 11;
  public static final int OR = 16;
  public static final int BOOL = 6;
  public static final int COMMA = 28;
  public static final int DIV = 20;
  public static final int DOUBLEDOT = 30;
  public static final int RP = 12;
  public static final int UNTIL = 8;
  public static final int PLUS = 17;
  public static final int MIN = 19;
  public static final int ASSIGN = 29;
  public static final int MAIN = 2;
  public static final int ID = 31;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int NEQ = 26;
  public static final int EQ = 25;
  public static final int REAL = 5;
  public static final int READ = 9;
  public static final int CHARCONST = 33;
  public static final int REALCONST = 35;
  public static final int BOOLCONST = 34;
  public static final int GREATE = 24;
}

